### ISSUE TITLE
Playlist like bloglist feature

### ISSUE THREAD

**Issue by SH20RAJ** [SH20RAJ/ShadeV3#35]

**Comment by SH20RAJ** [comment]
People can create list of blogs or GitBook Alternative Kindof

**Comment by SH20RAJ** [comment]
### Sub-Issues
   - [ ] #11: Sub-task 1 description
   - [ ] #12: Sub-task 2 description
   - [ ] #13: Sub-task 3 description
